/**
 * Tiny offline bonus dictionary for Easy gem Match extras.
 * Bill: Set lookup, straight-line only, length 3–6. BED must be in the set.
 * Planted extras are a fresh shuffle from this dict — not a fixed five.
 */

export const BONUS_WORD_MIN = 3
export const BONUS_WORD_MAX = 6

/**
 * Rude / crude / slang / insult / adult. Stay in the raw dump for size,
 * but never plant or score as candy extras.
 * Ordinary real English (SNAG, SNAP, BED, …) must stay off this list.
 */
const SKIP_BONUS = new Set([
  'NUDE',
  'NAKED',
  'SEX',
  'SEXY',
  'PORN',
  'BOOB',
  'BOOBS',
  'BUTT',
  'ARSE',
  'ASS',
  'BUM',
  'DICK',
  'COCK',
  'TIT',
  'TITS',
  'PISS',
  'CRAP',
  'POOP',
  'FART',
  'DAMN',
  'HELL',
  'SUCK',
  'SLUR',
  'SLUT',
  'RUMP',
  'VICE',
  'VIRGIN',
  'PANT',
  'HOLE',
  'WEED',
  'GIN',
  'RUM',
  'POT',
  'DOPE',
  'DRUG',
  'HUNG',
  'DUMB',
  'UGLY',
  'FAT',
  'LAZY',
  'LIAR',
  'LYING',
  'SLOB',
  'SNOB',
  'SMUG',
  'THUG',
  'PUNK',
  'WIMP',
  'STAB',
  'MURDER',
  'KILLED',
  'KILL',
  'HATE',
  'SLUM',
  'GUN',
  'WAR',
  'DYING',
  'DEATH',
  'DEAD',
  'DIE',
  'DIED',
  'BLOOD',
  'WOUND',
  'EVIL',
  'SIN',
  'ATTACK',
  'CRIME',
  'FRAUD',
  'ENEMY',
  'CANCER',
  'VIRUS',
  'WHIP',
])

/**
 * Common nouns and verbs we try first when planting. Shuffled per board
 * so extras change; the rest of the kid-friendly dict fills if needed.
 */
const PLANT_PREFER_RAW = `
BED CAT HAT RUN SON GAP YES NET BAG BAT MAT RAT SAT CAP TAP TAG
SUN FUN BUN CUP CUT HUG PAD PAN PEN PET MAP MAN DAY DIG DIP DOG
DOT EAR EAT FAN FAR FIG FIN FLY JAM JAR JAW JOB JOY KEY KID KIT
LAB LAP LAW LEG LID LIP LOG LOT MUG NAP NUT OAK OWL PAL PAW PAY
PEA PIE PIG PIN POP PUP RAG RED RUG SAD SAW SAY SEA SET SIP SIT
SUM TEA TEN TIE TIN TIP TOE TOP TOY TRY TUB VAN WIN YAM BALL BELL
BEAR DEER DUCK FROG GOAT LAMB BABY GIRL BOAT COAT GOWN MOON RAIN
SNOW TREE REST BEST NEST TEST GIVE FIVE NINE FINE COME DONE LOVE
LIVE BARN BIRD BLUE BOOK CAKE CALM CAMP CARD CART CAVE COIN COLD
CORN DARK DISH DOOR DOWN DRAW DRUM FACE FAIR FARM FAST FIRE FISH
FLAG FLAT FLOW FOOD FOOT FORT GAME GATE GOLD GOOD GROW HAND HEAD
HEAL HEAR HEAT HIDE HOLD HOLE HOLY HOUR HUNT IRON JOIN JUMP KEEP
KISS KITE LAKE LAND LANE LAST LEFT LIFE LIFT LION LIST LONG LOOK
LORD LOST LUCK MADE MAIL MAKE MARK MEAL MEAN MELT MILK MIND MINE
NAME NEAR NEED NOSE NOTE OPEN PACK PAGE PAIR PARK PART PASS PATH
PICK PILE PINK PLAN PLAY PLOT POND POUR PRAY PULL PUSH RAIL READ
REAL RIDE RISE ROCK ROLL ROOF ROOM ROSE SAFE SAIL SALE SALT SAND
SAVE SEAL SEED SEEK SEND SHIP SHOP SHOW SHUT SIDE SIGN SILK SING
SINK SLIP SLOW SOAP SOFT SOIL SONG SOON SORT SPIN SPOT STEP STOP
SURE SWIM TALE TALK TALL TEAM TELL TENT TIDE TIME TINY TIRE TOOL
TOWN TRIP TURN WAIT WALK WALL WANT WARM WASH WAVE WEAR WEEK WELL
WIDE WILD WIND WING WIRE WISH WOLF WOOD WORD WORK WRAP YARD YEAR
CARE KIND HELP ROAD GIFT HOME ARMS RING LAMP HILL CITY LIGHT SKY
STAR DAWN HEART GRACE CROSS PEACE TRUTH MERCY HOPE KING
BACK BAKE BAND BANK BARK BASE BATH BEAM BEAN BEAT BELT BIKE BITE
BLOW BOIL BOOT BURN BUSH CALL CAME COOK COOL CORN CROW CURE DEER
DESK DOLL DOVE DRAW DROP DUCK DUST EARN EAST EASY FACE FALL FARM
FEEL FEET FILL FIND FISH FIVE FLAG FLAT FLOW FOLD FOOD FOOT FORT
FOUR FULL GAME GATE GIFT GIRL GIVE GLAD GLOW GOAL GOAT GOLD GOOD
GRAB GROW HAIR HALF HALL HAND HARD HEAD HEAL HEAP HEAR HEAT HELP
HERD HERO HIDE HIGH HILL HOLD HOLE HOME HOOK HOPE HORN HOSE HOST
HOUR HUGE HUNT HURT JAIL JOKE JUMP JUST KEEP KICK KIND KING KISS
KITE KNEE KNOW LACE LADY LAKE LAMB LAMP LAND LANE LAST LATE LAWN
LEAD LEAF LEAN LEFT LIFE LIFT LIKE LILY LIME LINE LINK LION LIST
LIVE LOAD LOCK LONG LOOK LOOP LORD LOSE LOST LOUD LOVE LUCK MADE
MAIL MAIN MAKE MANY MARK MASK MATE MEAL MEAN MEAT MEET MELT MILE
MILK MILL MIND MINE MINT MOON MORE MOST MOVE MUCH MUST NAME NEAR
NEAT NECK NEED NEST NEWS NEXT NICE NINE NOSE NOTE OPEN PACK PAGE
PAID PAIL PAIN PAIR PARK PART PASS PAST PATH PEAK PEAR PICK PILE
PINE PINK PIPE PLAN PLAY PLOT PLOW PLUM PLUS POEM POET POLE POND
PONY POOL PORT POST POUR PRAY PULL PUMP PURE PUSH RACE RAFT RAIL
RAIN RAKE READ REAL REST RICE RICH RIDE RING ROAD ROCK ROLL ROOF
ROOM ROOT ROPE ROSE SAFE SAIL SALE SALT SAND SAVE SEAL SEED SEEK
SEND SHIP SHOE SHOP SHOW SHUT SIDE SIGN SILK SING SINK SKIP SLIP
SLOW SNOW SOAP SOFT SOIL SONG SOON SORT SOUP SPIN SPOT STAR STAY
STEP STOP SWAN SWIM TAIL TAKE TALE TALK TALL TAME TANK TAPE TEAM
TELL TENT TEST TIDE TIME TINY TIRE TOAD TOLD TONE TOOL TOWN TOY
TRAP TRAY TREE TRIM TRIP TRUE TUBE TUNE TURN TWIN WALK WALL WANT
WARM WASH WAVE WEAR WEEK WELL WENT WEST WIDE WIFE WILD WIND WINE
WING WISH WOLF WOOD WOOL WORD WORK WORM WRAP YARD YARN YEAR YOGA
APPLE BEACH BREAD BRING BROWN BUILD CARRY CATCH CHAIR CHART CHEST
CHILD CLASS CLEAN CLEAR CLIMB CLOCK CLOSE CLOUD COACH COAST COUNT
COVER CREAM CROSS DANCE DREAM DRESS DRINK DRIVE EARTH EIGHT EMPTY
ENJOY ENTER EVERY FAITH FIELD FIGHT FIRST FLOOR FOCUS FORCE FOUND
FRESH FRUIT FUNNY GLASS GRACE GRADE GRAIN GRAPE GRASS GREAT GREEN
GROUP GROWN GUARD GUIDE HAPPY HEART HEAVY HORSE HOTEL HOUSE HUMAN
JUICE LARGE LAUGH LEARN LEAVE LIGHT LUNCH MAGIC MARCH MATCH MAYBE
METAL MIGHT MONEY MONTH MOUSE MOUTH MUSIC NIGHT NOISE NORTH NURSE
OCEAN OFFER OFTEN ORDER PAINT PAPER PARTY PEACE PHONE PHOTO PIECE
PLACE PLAIN PLANE PLANT PLATE POINT POWER PRESS PRICE PRIZE PROUD
QUICK QUIET RADIO RIVER ROUND SCALE SCENE SCORE SEVEN SHAPE SHARE
SHARP SHEET SHELF SHELL SHIFT SHIRT SHORT SIGHT SKILL SLEEP SMALL
SMART SMILE SMOKE SNAKE SOUND SOUTH SPACE SPEAK SPEED SPEND SPORT
STAIR STAND START STEAM STEEL STICK STONE STORE STORM STORY SUGAR
SWEET SWING TABLE TASTE TEACH TEETH THANK THING THINK THREE TIGHT
TODAY TOOTH TOUCH TOWER TRACK TRAIN TREAT TRUCK TRUST TRUTH UNCLE
VALUE VIDEO VISIT VOICE WATCH WATER WHEEL WHITE WHOLE WOMAN WORLD
WRITE YOUNG YOUTH ANIMAL ANSWER AROUND ARTIST BOTTLE BOTTOM BRANCH
BRIDGE BRIGHT BROKEN BUTTON CAMERA CASTLE CENTER CHANCE CHANGE
CHOICE CHOOSE CHURCH CIRCLE CLOSER COFFEE COMMON CORNER COUPLE
COURSE CREATE DANGER DEBATE DOCTOR DOLLAR DOUBLE DRIVER DURING
ELEVEN EMPIRE ENERGY ENGINE ENOUGH ESCAPE FAMILY FAMOUS FATHER
FELLOW FLOWER FOREST FRIEND FUTURE GARDEN GATHER GENTLE GLOBAL
GOLDEN GROUND GROWTH GUITAR HANDLE HAPPEN HEALTH HONEST ISLAND
LEADER LEAVES LENGTH LESSON LETTER LISTEN LITTLE LIVING LOVELY
MAKING MARKET MASTER MATTER MEMBER MEMORY MIDDLE MINUTE MIRROR
MOBILE MODERN MOMENT MOTHER MOTION NARROW NATION NATURE NOTICE
NUMBER OFFICE ORANGE PARENT PEOPLE PERSON PLANET PLAYER PLEASE
POCKET PUBLIC PURPLE RATHER REALLY REASON RECORD RELIEF REMAIN
REPAIR REPEAT REPORT RESCUE RESULT RETURN REWARD SAFETY SCHOOL
SEASON SECOND SILENT SILVER SIMPLE SINGLE SISTER SMOOTH SOURCE
SPEECH SPIRIT SPRING SQUARE STREET STRONG SUMMER SUPPLY SWITCH
TARGET TEMPLE THANKS THIRTY TICKET TRAVEL TWELVE TWENTY VALLEY
WINDOW WINNER WINTER WISDOM WONDER WORKER WRITER YELLOW
`.trim()

const RAW = `
BED CAT HAT RUN SON GAP YES NET
GAP CAP TAP TAG BAG BAT MAT PAT RAT SAT VAT
GEM GUM GUN HUG SUN FUN BUN CUP CUT
CARE KIND HELP ROAD GIFT HOME ARMS RING
OIL INN HURT DEBT KING JAIL
LAMP HILL CITY LIGHT SKY STAR TOLD DAWN TOMB
HEART GRACE CROSS PEACE TRUTH MERCY LOVE HOPE
PAD PAN PEN PET PIT POT PUT MAP MAN MEN
BIG BIT BUS DAY DIG DIP DOG DOT DRY EAR EAT
END FAN FAR FED FIG FIN FIT FLY FUR
GET GOT HER HIS HIM YOU SHE HAM HEN HID HIP HIT HOP HOT HUM HUT
JAM JAR JAW JET JOB JOY KEY KID KIT LAB LAP
LAW LAY LED LEG LET LID LIP LIT LOG LOT LOW
MAD MUD MUG NAP NEW NOD NUT OAK
OAR OAT ODD OLD OWL PAL
PAW PAY PEA PIE PIG PIN POD
POP PUN PUP RAG RAN RAP RAW RAY
RED RID RIG RIM RIP ROB ROD ROT ROW RUB
RUG SAD SAG SAW SAY SEA SET SIP
SIR SIT SIX SOB SOW SPA SPY SUM
TAB TAN TAR TEA TEN TIE TIN
TIP TOE TON TOP TOW TOY TRY TUB TUG VAN
WAG WAR WAX WAY WEB WED WET WIN WIT WON
YAM YET
BAD BET BID BUD BOX FOX MIX FIX ZIP
CAR BAR DAD MOM BOY COW BEE ANT APE ARM ART
ASH ASK BAN BAY BEG BIN BOW BUG BUY
CAB CAN COB COD COP COT CRY CUB
DAB DAM DEN DEW DID DIE DIM DOE DUG DYE
EEL EGG ELF ELK ELM EMU EVE EYE
FAD FAX FEE FEW FIB FIR FOE FOG FRY
GAS GEL GIG GIN GOD GUT GYM
HAD HAY HEM HEY HOE HOG HUB HUE
ICE ICY ILL IMP INK IVY
JAB JAY JIG JOG JOT JUG
KEG KIN LAD LAG LAM LAX LIE
MET MID MOO MOP MOW MUM
NAB NAG NAY NIP NIT NOW
ODE ORB ORE OWE
PEG PEP PER PEW PLY PRY
RAM RIB RUM RUT RYE
SAP SEE SEW SHE SHY SIN SKI SLY
SOD SOL SOY SUB SUE TWO
USE VET VOW WIG WOE WOW
YAK YAY YEP YEW YUM ZAP ZIP ZOO
BALL BELL BEAR DEER DUCK FROG GOAT LAMB BABY GIRL
BOAT COAT GOWN MOON RAIN SNOW TREE REST BEST NEST
TEST EAST PAST CAST DUST RUST COST POST HOST
GIVE FIVE NINE FINE COME DONE NONE GONE ZONE
LOVE LIVE BONE LONE TONE
BARN BIRD BLUE BOLD BOND BOOK BORN
CAKE CALM CAMP CARD CART CAVE COIN COLD
CORN DARK DISH DOOR DOWN DRAW DRUM
FACE FAIR FARM FAST FEAR FIRE FISH FLAG
FLAT FLOW FOOD FOOT FORT GAME GATE GOLD
GOOD GROW HAND HANG HARD HARM HEAD HEAL
HEAR HEAT HIDE HOLD HOLE HOLY HOUR HUNT
IRON JOIN JUMP KEEP KISS KITE
LAKE LAND LANE LAST LEFT LIFE LIFT
LION LIST LONG LOOK LORD LOST LUCK MADE
MAIL MAKE MARK MEAL MEAN MELT MILK MIND
MINE NAME NEAR NEAT NEED NOSE
NOTE OPEN PACK PAGE PAIN PAIR PARK PART
PASS PATH PICK PILE PINK PLAN PLAY PLOT
PLUS POND POUR PRAY PULL PUSH RAIL
READ REAL RIDE RISE ROCK ROLL
ROOF ROOM ROSE SAFE SAIL SALE SALT SAND
SAVE SEAL SEED SEEK SEEM SELF SEND SHIP
SHOP SHOW SHUT SIDE SIGN SILK SING SINK
SLIP SLOW SOAP SOFT SOIL SONG SOON
SORT SPIN SPOT STEP STOP SURE
SWIM TALE TALK TALL TAME TEAM TELL TENT
TIDE TIME TINY TIRE TONE TOOL TORN TOWN TRIP
TURN UNDO UNIT UPON USED VAST VIEW
WAIT WALK WALL WANT WARM WARN WASH WAVE
WEAK WEAR WEEK WELL WENT WEST WIDE WIFE
WILD WIND WINE WING WIRE WISH WOLF WOOD
WORD WORK WORM WRAP YARD YEAR
ABLE ACHE ACID ACRE AGED AIDE AIRS ALLY ALSO AREA ARID ARMY ARTS ATOM AUNT AUTO AWAY AXIS
BACK BAIT BAKE BAND BANG BANK BARE BARK BASE BASH BASS BATH BEAD BEAK BEAM BEAN BEAT BEEN
BELT BEND BENT BIAS BIKE BILE BILL BIND BITE BLEW BLOW BOIL BOLD BOLT BOND BONE BOOM BOOT
BORE BOSS BOTH BRAG BRAN BRIM BROW BUCK BULB BULK BULL BUMP BURN BUSH BUSY
CAGE CALL CALM CAME CARD CARE CART CASE CASH CAST CAVE CHIP CHIN CHOP CLAM CLAP CLAW CLAY
CLIP CLUB CLUE COAL COAT CODE COLT COMB COOK COOL CORD CORE CORK CORN COST COZY CRAB CREW
CROP CROW CUBE CURE CURL CUTE
DAMP DARE DART DATE DAWN DEAL DEAR DECK DEED DEEP DEER DESK DIAL DICE DINE DIRT DISH DIVE
DOCK DOLL DOME DOOM DOSE DOVE DOWN DRAG DRAW DREW DRIP DROP DRUM DUAL DUCK DUEL DUET DULL
DULY DUMB DUMP DUNE DUSK DUST DUTY
EARN EASE EAST EASY EDGE EDIT EGOS ELBO ELSE EMIT ENVY EPIC EVEN EVER EVIL
FACT FADE FAIL FAIR FALL FAME FARE FARM FAST FATE FEAR FEED FEEL FEET FELL FELT FILE FILL
FILM FIND FIRM FISH FIST FIVE FLAG FLAT FLEA FLED FLEE FLEW FLEX FLIP FLOW FOAM FOLD FOLK
FOND FONT FOOD FOOL FOOT FORD FORK FORM FORT FOUL FOUR FREE FRET FROM FUEL FULL FUME FUND
FURY FUSE FUSS
GAIN GALA GALE GAME GANG GASP GATE GAVE GAZE GEAR GENT GIFT GILL GIRL GIVE GLAD GLOW GLUE
GOAL GOAT GOES GOLD GOLF GONE GONG GOOD GORE GOSH GRAB GRAD GRAM GRAY GREW GRID GRIM GRIN
GRIP GROW GULF GULL GUST
HAIL HAIR HALF HALL HALT HAND HANG HARD HARE HARM HARP HATE HAVE HAWK HEAD HEAL HEAP HEAR
HEAT HEEL HELD HELL HELP HERB HERD HERE HERO HIDE HIGH HILL HINT HIRE HIVE HOLD HOLE HOLY
HOME HONEY HOOK HOOP HOPE HORN HOSE HOST HOUR HOWL HUGE HULL HUNG HUNT HURT HUSH HYMN
ICED ICON IDEA IDLE IDOL INCH INFO IRON ISLE ITEM
JADE JAIL JOKE JOLT JUMP JURY JUST
KEEL KEEP KEPT KICK KIND KING KISS KITE KNEE KNEW KNIT KNOB KNOT KNOW
LACE LACK LADY LAID LAIN LAIR LAKE LAMB LAME LAMP LAND LANE LARK LASH LAST LATE LAVA LAWN
LAZY LEAD LEAF LEAK LEAN LEAP LEFT LEND LENS LENT LESS LEVY LIAR LICE LICK LIED LIFE LIFT
LIKE LILY LIMB LIME LIMP LINE LINK LINT LION LIST LIVE LOAD LOAF LOAN LOCK LOFT LOGS LONE
LONG LOOK LOOP LORD LOSE LOSS LOST LOUD LOVE LUCK LULL LUMP LUNG LURE LUSH LUTE
MADE MAID MAIL MAIN MAKE MALE MALL MALT MANE MANY MARE MARK MARS MASK MASS MAST MATE MATH
MAZE MEAL MEAN MEAT MEET MELT MEMO MEND MENU MERE MESH MESS MICE MILD MILE MILK MILL MIND
MINE MINT MISS MIST MOAT MOCK MODE MOLD MOLE MONK MOOD MOON MOOR MOOT MORE MOSS MOST MOTH
MOVE MUCH MULE MUSE MUST MYTH
NAIL NAME NAVY NEAR NEAT NECK NEED NEST NEWS NEWT NEXT NICE NINE NODE NONE NOON NORM NOSE
NOTE NOUN NOVA NUDE NULL NUMB
OAKS OARS OATH OATS OBEY OILS OKAY ONES ONTO OPEN ORAL ORES OURS OVAL OVEN OVER OWED OWES
OWLS OXEN
PACE PACK PACT PAGE PAID PAIL PAIN PAIR PALE PALM PANE PANS PANT PARK PART PASS PAST PATH
PAVE PAWN PEAK PEAR PEAS PEAT PECK PEEL PEER PELT PERK PEST PICK PIER PIKE PILE PILL PINE
PINK PINT PIPE PITY PLAN PLAY PLEA PLED PLOT PLOW PLOY PLUG PLUM PLUS POEM POET POKE POLE
POLL POND PONY POOL POOR POPE PORK PORT POSE POST POUR POUT PRAY PREY PROP PROW PULL PULP
PUMP PUNK PUNT PUPIL PURE PUSH
QUIT QUIZ
RACE RACK RAFT RAGE RAID RAIL RAIN RAKE RAMP RANG RANK RARE RASH RATE RATS RAVE READ REAL
REAP REAR REED REEL REIN RELY RENT REST RIBS RICE RICH RIDE RIFE RIFT RIGS RILE RIND RING
RIOT RISE RISK RITE ROAD ROAM ROAR ROBE ROCK RODE ROLE ROLL ROOF ROOM ROOT ROPE ROSE ROSY
ROTE ROUT ROWS RUBY RUDE RUGS RUIN RULE RUMP RUNE RUNG RUNT RUSH RUST RUTH
SACK SAFE SAGA SAGE SAID SAIL SAKE SALE SALT SAME SAND SANE SANG SANK SASH SAVE SAWS SCAB
SCAR SEAL SEAM SEAR SEAT SEED SEEK SEEM SEEN SEES SELF SELL SEND SENT SHED SHIM SHIN SHIP
SHOE SHOP SHOT SHOW SHUT SICK SIDE SIGH SIGN SILK SILL SILO SILT SINE SING SINK SIRE SITE
SITS SIZE SKEW SKID SKIM SKIN SKIP SKIT SLAB SLAM SLAP SLAT SLAW SLAY SLED SLEW SLID SLIM
SLIP SLIT SLOB SLOT SLOW SLUG SLUM SLUR SMOG SMUG SNAG SNAP SNIP SNOB SNOW SNUG SOAK SOAP
SOAR SOCK SODA SOFA SOFT SOIL SOLD SOLE SOME SONG SOON SOOT SORE SORT SOUL SOUP SOUR SOWN
SPAN SPAR SPAT SPIN SPIT SPOT SPUN SPUR STAB STAG STAR STAY STEM STEP STEW STIR STOP STOW
STUB STUD STUN SUCH SUCK SUDS SUIT SULK SUMS SUNG SUNK SURE SURF SWAM SWAN SWAP SWAT SWAY
SWIM SWUM
TACK TACT TAIL TAKE TALE TALK TALL TAME TANK TAPE TAPS TART TASK TAUT TAXI TEAK TEAL TEAM
TEAR TEAS TEED TEEM TEEN TELL TEND TENT TERM TEST TEXT THAN THAT THAW THEE THEM THEN THEY
THIN THIS THOU THUD THUG THUS TICK TIDE TIDY TIED TIER TILE TILL TILT TIME TINE TINT TINY
TIRE TOAD TOIL TOLD TOLL TOMB TONE TONG TOOK TOOL TORN TOSS TOTE TOUR TOWN TOYS TRAM TRAP
TRAY TREE TREK TRIM TRIO TRIP TROD TROT TRUE TUBA TUBE TUCK TUNA TUNE TURF TURN TUSK TWIN
TYPE
UGLY UNIT UNTO UPON URGE USED USER USES
VAIN VALE VANE VARY VASE VAST VEIL VEIN VENT VERB VERY VEST VETO VIAL VICE VIEW VILE VINE
VISA VOID VOLT VOTE
WADE WAGE WAIL WAIT WAKE WALK WALL WAND WANT WARD WARM WARN WARP WART WASH WASP WATT WAVE
WAXY WAYS WEAK WEAR WEED WEEK WEEP WELD WELL WENT WEPT WERE WEST WHAM WHAT WHEN WHET WHEY
WHIP WHIR WHIT WHOA WHOM WICK WIDE WIFE WILD WILL WILT WILY WIMP WIND WINE WING WINK WIPE
WIRE WISE WISH WISP WITH WITS WOKE WOLF WOMB WOOD WOOF WOOL WORD WORE WORK WORM WORN WRAP
WRIT
YARD YARN YAWN YEAR YELL YELP YOGA YORK YOUR
ZEAL ZERO ZEST ZONE ZOOM
ABOUT ABOVE ACTOR ACUTE ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD ALARM ALBUM ALERT
ALIKE ALIVE ALLOW ALONE ALONG ALTER AMONG ANGER ANGLE ANGRY APART APPLE APPLY AREAS ARGUE
ARISE ASIDE ASKED ASSET AVOID AWARD AWARE AWFUL
BASIC BASIS BEACH BEGAN BEGIN BEING BELOW BENCH BILLY BIRTH BLACK BLADE BLAME BLANK BLAST
BLIND BLOCK BLOOD BOARD BOOST BOOTH BOUND BRAIN BRAND BREAD BREAK BREED BRICK BRIDE BRIEF
BRING BROAD BROKE BROWN BRUSH BUILD BUILT BUNCH BUYER
CABLE CALIF CARRY CATCH CAUSE CHAIN CHAIR CHART CHASE CHEAP CHECK CHEST CHIEF CHILD CHINA
CHOSE CIVIL CLAIM CLASS CLEAN CLEAR CLICK CLIMB CLOCK CLOSE CLOTH CLOUD COACH COAST COULD
COUNT COURT COVER CRAFT CRASH CREAM CRIME CROSS CROWD CROWN CURVE CYCLE
DAILY DANCE DATED DEALT DEATH BEGIN DEPTH DIRTY DOING DOUBT DOZEN DRAFT DRAMA DRANK DREAM
DRESS DRILL DRINK DRIVE DROVE DYING
EAGER EARLY EARTH EIGHT ELITE EMPTY ENEMY ENJOY ENTER ENTRY EQUAL ERROR EVENT EVERY EXACT
EXIST EXTRA
FAITH FALSE FAULT FEWER FIELD FIFTH FIFTY FIGHT FINAL FIRST FIXED FLASH FLEET FLOOR FLUID
FOCUS FORCE FORTH FORTY FORUM FOUND FRAME FRANK FRAUD FRESH FRONT FRUIT FULLY FUNNY
GIANT GIVEN GLASS GLOBE GOING GRACE GRADE GRAIN GRAND GRANT GRAPE GRAPH GRASS GRAVE GREAT
GREEN GROSS GROUP GROWN GUARD GUESS GUEST GUIDE
HAPPY HARRY HEART HEAVY HENCE HORSE HOTEL HOUSE HUMAN
IDEAL IMAGE INDEX INNER INPUT ISSUE
JOINT JONES JUDGE JUICE
KNOWN
LABEL LABOR LARGE LAUGH LAYER LEARN LEAST LEAVE LEGAL LEVEL LIGHT LIMIT LIVES LOCAL LOGIC
LOOSE LOWER LUCKY LUNCH LYING
MAGIC MAJOR MAKER MARCH MATCH MAYBE MAYOR MEANT MEDIA METAL MIGHT MINOR MINUS MIXED MODEL
MONEY MONTH MORAL MOTOR MOUNT MOUSE MOUTH MOVED MOVIE MUSIC
NEEDS NEVER NIGHT NOISE NORTH NOTED NOVEL NURSE
OCCUR OCEAN OFFER OFTEN ORDER OTHER OUGHT OUTER OWNED OWNER
PAINT PANEL PAPER PARKY PARTY PASTE PATCH PEACE PHASE PHONE PHOTO PIECE PILOT PITCH PLACE
PLAIN PLANE PLANT PLATE POINT POUND POWER PRESS PRICE PRIDE PRIME PRINT PRIOR PRIZE PROOF
PROUD PROVE
QUICK QUIET QUITE
RADIO RAISE RANGE RAPID RATIO REACH READY REFER RIGHT RIVAL RIVER ROUGH ROUND ROUTE ROYAL
RURAL
SCALE SCENE SCOPE SCORE SENSE SERVE SEVEN SHALL SHAPE SHARE SHARP SHEET SHELF SHELL SHIFT
SHIRT SHOCK SHOOT SHORT SHOWN SIDES SIGHT SINCE SIXTH SIXTY SIZED SKILL SLEEP SLIDE SMALL
SMART SMILE SMITH SMOKE SNAKE SNOWY SOLID SOLVE SORRY SOUND SOUTH SPACE SPARE SPEAK SPEED
SPEND SPENT SPLIT SPOKE SPORT STAFF STAGE STAIR STAKE STAND START STATE STEAM STEEL STICK
STILL STOCK STONE STOOD STORE STORM STORY STRAP STRAW STRIP STUCK STUDY STUFF STYLE SUGAR
SUITE SUPER SWEET SWEPT SWIFT SWING SWORD
TABLE TAKEN TASTE TAXES TEACH TEETH THANK THEIR THEME THERE THESE THICK THING THINK THIRD
THOSE THREE THREW THROW TIGHT TIMES TIRED TITLE TODAY TOKEN TOOTH TOPIC TOTAL TOUCH TOUGH
TOWER TRACK TRADE TRAIN TREAT TREND TRIAL TRIED TRIES TRUCK TRULY TRUST TRUTH TWICE TWINS
TWIST TYPED TYPES
UNCLE UNDER UNITS UNTIL UPPER UPSET URBAN USAGE USUAL
VALID VALUE VIDEO VIRUS VISIT VITAL VOICE
WASTE WATCH WATER WHEEL WHERE WHICH WHILE WHITE WHOLE WHOSE WOMAN WOMEN WORLD WORRY WORSE
WORST WORTH WOULD WOUND WRITE WRONG WROTE
YIELD YOUNG YOURS YOUTH
ABROAD ACCEPT ACCESS ACROSS ACTING ACTION ACTIVE ACTUAL ADVICE ADVISE AFFECT AFFORD AFRAID
AGENCY AGENDA ALMOST ALWAYS AMOUNT ANIMAL ANNUAL ANSWER ANYONE ANYWAY APPEAL APPEAR AROUND
ARRIVE ARTIST ASPECT ASSESS ASSIGN ASSIST ASSUME ATTACK ATTEND AUTHOR
BARELY BATTLE BEAUTY BECAME BECOME BEFORE BEHALF BEHAVE BEHIND BELIEF BELONG BESIDE BETTER
BEYOND BOARDER BORDER BOTTLE BOTTOM BOUGHT BRANCH BREATH BRIDGE BRIGHT BROKEN BUDGET BURDEN
BUREAU BUTTON
CAMERA CAMPUS CANCER CANNOT CARBON CAREER CASTLE CASUAL CAUGHT CENTER CHANCE CHANGE CHARGE
CHOICE CHOOSE CHOSEN CHURCH CIRCLE CLIENT CLOSED CLOSER COFFEE COLUMN COMBAT COMING COMMON
COPPER CORNER COSTLY COUNTY COUPLE COURSE COVERS CREATE CREDIT CRISIS CUSTOM
DAMAGE DANGER DEALER DEBATE DECADE DECIDED DEFEAT DEFEND DEFINE DEGREE DEMAND DEPEND DEPUTY
DESERT DESIGN DESIRE DETAIL DETECT DEVICE DIFFER DINNER DIRECT DOCTOR DOLLAR DOMAIN DOUBLE
DRIVEN DRIVER DURING
EASILY EATING EDITOR EFFECT EFFORT EITHER ELEVEN EMERGE EMPIRE EMPLOY ENABLE ENERGY ENGAGE
ENGINE ENOUGH ENSURE ENTIRE ENTITY ESCAPE ESTATE ETHICS ETHNIC EUROPE EXCEPT EXCESS EXPAND
EXPECT EXPERT EXPORT EXTEND EXTENT
FABRIC FACING FACTOR FAILED FAMILY FAMOUS FATHER FELLOW FEMALE FIGURE FILING FINGER FINISH
FLIGHT FLOWER FLYING FOLLOW FORCED FOREST FORGOT FORMAL FORMAT FORMER FOSTER FOUGHT FOURTH
FRENCH FRIEND FROZEN FUTURE
GALAXY GARDEN GATHER GENDER GENTLE GERMAN GLOBAL GOLDEN GROUND GROWTH GUILTY GUITAR
HANDED HANDLE HAPPEN HARBOR HARDLY HEADED HEALTH HELPED HEROES HIDDEN HOLDER HONEST IMPACT
INCOME INDEED INJURY INSIDE INTENT INVEST ISLAND ITSELF
JERSEY JOSEPH JUNIOR JUNGLE
KERNEL KIDNEY KILLED
LATTER LAUNCH LAWYER LEADER LEAGUE LEAVES LENGTH LESSON LETTER LIKELY LINKED LIQUID LISTEN
LITTLE LIVING LOADED LOSING LOVELY LOVING
MAKING MANAGE MANNER MANUAL MARGIN MARINE MARKED MARKET MASTER MATTER MATURE MEDIUM MEMBER
MEMORY MENTAL MERELY METHOD MIDDLE MILLER MINUTE MIRROR MOBILE MODERN MODEST MODULE MOMENT
MORRIS MOSTLY MOTHER MOTION MOVING MURDER MUSCLE MUSEUM MUTUAL MYSELF
NARROW NATION NATIVE NATURE NEARBY NEARLY NINETY NOBODY NORMAL NOTICE NUMBER
OBJECT OBTAIN OFFICE OFFSET ONLINE OPTION ORANGE ORIGIN OUTPUT OXFORD
PACKED PALACE PARENT PARTLY PASSED PATENT PEOPLE PERIOD PERMIT PERSON PHRASE PICKED PLANET
PLAYER PLEASE PLENTY POCKET POLICE POLICY PREFER PRETTY PRIEST PRINCE PRISON PROFIT PROPER
PROVEN PUBLIC PURPLE
RACING RAISING RANGER RARELY RATHER RATING READER REALLY REASON RECALL RECENT RECORD REDUCE
REFORM REGARD REGION RELATE RELIEF REMAIN REMOTE REMOVE REPAIR REPEAT REPLAY REPORT RESCUE
RESORT RESULT RETAIL RETIRE RETURN REVEAL REVIEW REWARD RISING ROBUST ROLLING
SAFETY SALARY SAMPLE SAVING SAYING SCHEMA SCHOOL SCREEN SEARCH SEASON SECOND SECRET SECTOR
SECURE SEEING SELECT SELLER SENIOR SERIES SERVER SETTLE SEVERE SIGNAL SIGNED SILENT SILVER
SIMPLE SINGLE SISTER SLIGHT SLOWLY SMOOTH SOCCER SOCIAL SOLELY SOUGHT SOURCE SOVIET SPEECH
SPIRIT SPOKEN SPREAD SPRING SQUARE STABLE STOLEN STRAIN STRAND STREAM STREET STRICT STRIKE
STRING STRONG STRUCK STUDIO SUBMIT SUDDEN SUFFER SUMMER SUMMIT SUPPLY SURELY SURVEY SWITCH
SYMBOL SYSTEM
TAKING TALENT TARGET TAUGHT TEMPLE TENANT TENDER TENNIS THANKS THEORY THIRTY THOUGH THREAD
THREAT THROWN TICKET TIMING TISSUE TOWARD TRAVEL TREATY TRULYS TRYING TUNING TWELVE TWENTY
TYPING
UNABLE UNEASY UNION UNIQUE UNITED UNLESS UNLIKE UPDATE USEFUL
VALLEY VARIED VENDOR VERSUS VICTIM VIEWER VIRGIN VISION VISUAL VOLUME
WALKER WEALTH WEEKLY WEIGHT WHOLLY WINDOW WINNER WINTER WISDOM WITHIN WONDER WORKER WRIGHT
WRITER
YELLOW
`.trim()

function parseWords(source: string): Set<string> {
  const words = new Set<string>()
  for (const bit of source.split(/\s+/)) {
    const word = bit.toUpperCase()
    if (word.length >= BONUS_WORD_MIN && word.length <= BONUS_WORD_MAX) words.add(word)
  }
  return words
}

/** Common English extras. Lookup is O(1). */
export const COMMON_BONUS_WORDS: ReadonlySet<string> = parseWords(RAW)

export const COMMON_BONUS_COUNT = COMMON_BONUS_WORDS.size

const PLANT_PREFERS: ReadonlySet<string> = new Set(
  [...parseWords(PLANT_PREFER_RAW)].filter((word) => COMMON_BONUS_WORDS.has(word) && !SKIP_BONUS.has(word)),
)

export function isCommonBonusWord(text: string): boolean {
  return COMMON_BONUS_WORDS.has(text)
}

/** Skip rude / crude / slang / insult extras. Lesson pools may still score their own words. */
export function isKidFriendlyBonusWord(text: string): boolean {
  return !SKIP_BONUS.has(text.toUpperCase())
}

/** Common nouns and verbs — shuffled first when planting findable extras. */
export function isPreferredPlantWord(text: string): boolean {
  return PLANT_PREFERS.has(text.toUpperCase())
}

export function isPlantableBonusWord(text: string): boolean {
  const word = text.toUpperCase()
  return (
    word.length >= BONUS_WORD_MIN &&
    word.length <= BONUS_WORD_MAX &&
    COMMON_BONUS_WORDS.has(word) &&
    isKidFriendlyBonusWord(word)
  )
}
