/** Player-facing Easy chrome labels. Re-exported from easy.ts. */
export const EASY = {
  creed: 'old shared belief',
  parable: 'Jesus story',
  mindMap: 'your scrapbook of matches',
  mindMapShort: 'Scrapbook',
  connectLink: 'Tap the sentence, then the place, then the person.',
  matchHunt: 'Find a word. A story panel opens.',
  runHunt: 'Hold to run. Let go when it glows, then press again.',
  runCta: 'Run to him',
  runMatch: 'Run',
  runHome: 'One more run.',  // Easy Clear 1.4.155: short Home next-step (not full runHunt; Fixes #192)
  runAgain: 'One more run',
  mazeHunt: 'Find the hurt man. Help him. Take him to the inn.',
  mazeCta: 'Help on the road',
  mazeMatch: 'Help',
  mazeHome: 'One more road.',  // Easy Clear 1.4.155: short Home next-step (not full mazeHunt; Fixes #192)
  mazeWinWhy: 'You found him, helped him, and took him to safety.',
  mazeAgain: 'One more road',
  mergeHunt: 'Drop candy. Smash two of a kind.',
  mergeCta: 'Merge candy',
  mergeMatch: 'Merge',
  mergeHome: 'Drop candy. Smash two of a kind. Make the creed.',
  mergeWinWhy: 'Died, buried, raised, appeared.',
  digHunt: 'Scrub the dirt off each tablet. Dig the old names.',
  digCta: 'Dig the names',
  digMatch: 'Dig',
  digHome: 'Scrub the dirt off each tablet. Dig the old names. One more dig.',
  digAgain: 'One more dig',
  snapHunt: 'Tap when a beat is under the gate. Lock three. Story opens.',
  snapCta: 'Snap the story',
  snapMatch: 'Snap',
  snapHome: 'Tap when a beat is under the gate. Lock three. Story opens. One more snap.',
  snapAgain: 'One more snap',
  readStory: 'Read today’s story.',
  learnCta: 'Learn',
  readStoryFirst: 'Read the story first',
  learnThisFirst: 'Learn this first.',
  findGems: 'Find the gems',
  panelCue: 'Find a word to flip the first panel.',
  rememberSentence: 'Tap the main idea you kept.',
  tapWhy: 'Tap why this is true.',
  keepThis: 'Yes — keep this',
  holdYes: 'Yes!',
  holdLocked: 'LOCKED!',
  missPenalty: 'Miss −25',
  missTeachBadge: "Not quite — here's why",
  whyTrueLabel: 'Why this is true',
  tryAgain: 'Try again',
  oneMoreTry: 'One more try',
  holdKept: 'That’s the line.',
  bonusToast: 'BONUS! +100',
  bonusWhy: 'Extra try!',
  moreMatch: 'One more Match',
  bonusHint: 'Find lesson words — extras give +100 & another try',
  bonusMissWord: 'Not a bonus word',
  bonusMissStraight: 'Try a full straight word',
  fatherWinWhy: 'The father hugs him first.',
  readAgain: 'Read this one again.',
  claimTeach: 'A claim is the main idea we hold to be true.',
  mainIdeaTeach: 'Main idea = the short true line we keep.',
  mainIdea: 'main idea',
  reasonTeach: 'A reason is why this is true.',
  reasonSense: 'why this is true',
  sayWhy: 'Why this is true',
  whyStands: 'Why this is true.',
  sourceSense: 'where this comes from',
  sayFrom: 'From',
  sayTomorrow: 'Say this tomorrow',
  lockIn: 'Save your picks.',
  matchHow: 'Keep the right pictures. Remove wrong picks.',
  tapSentence: 'Tap a sentence',
  tapPlace: 'Tap a place',
  tapPerson: 'Tap a person',
  upgrade: 'Build this — raise the next look you earned by learning',
  manage: 'Manage',
  matchCta: 'Match',
  matchDone: 'Match done',
  matchWin: 'Matched!',
  holdNext: 'Lock In next',
  continueStreet: 'Continue tonight’s street',
  nightDo: 'Night Watch',
  nightSoon: 'Night Watch (soon)',
  nightTap: 'Tap the face.',
  nightLead: 'Tap the face six times.',
  nightMiss: 'Wrong — tap the glowing face',
  startEasy: 'Start Easy',
  welcomeEyebrow: 'A short trail',
  welcomeTag: 'Reasons to believe',
  welcomeGoal: 'Play short puzzles. Keep the reasons you can trust.',
  welcomeNote: 'Bigger taps. Clear words.',
  home: 'Home',
  townSoon: 'Town (soon)',
  supportTrail: 'Support the trail',
  removeAds: 'Remove ads',
  packs: 'Street Packs',
  tip: 'Tip',
  loveCue: 'Love — when compassion moves you, help like the Samaritan. Tap the glowing face.',
  deployTeach: 'Use a main idea you kept.',
  saved: 'Lock In',
  savedSub: 'saved lines',
  connections: 'Connections',
  uses: 'Things you can use',
  resetWalk: 'Reset this Easy walk',
} as const
