import type { JournalEntry } from '../types'

export const journalEntries: JournalEntry[] = [
  {
    id: 'j-ph-1',
    areaId: 'parable-hollow',
    title: 'The Teacher who taught in stories',
    kicker: 'Parable Hollow',
    unlockAfter: 'ph-road',
    body: [
      'The Gospels present Jesus as a teacher whose most characteristic form is the parable. These are not children’s decorations added to a lecture. They are the lecture — they force a decision about mercy, pride, and the identity of God.',
      'The Good Samaritan (Luke 10:25–37) relocates the word “neighbor” from a boundary question to a mercy question. The listener is not first invited to classify others. The listener is invited to become the kind of person who crosses the road.',
    ],
    sources: ['Luke 10:25–37', 'Luke 10:29'],
  },
  {
    id: 'j-ph-2',
    areaId: 'parable-hollow',
    title: 'Mercy that runs',
    kicker: 'Parable Hollow',
    unlockAfter: 'ph-father',
    body: [
      'Luke 15 stacks three lost-and-found stories after a complaint: this man welcomes sinners and eats with them. The father’s run (Luke 15:20) is the theological center of the third story. Honor is spent so that the son can be embraced before he finishes his hired-hand speech.',
      'The older brother shows that you can live in the house and still refuse the feast. Nearness without joy at another’s return is a second lostness.',
    ],
    sources: ['Luke 15:1–32'],
  },
  {
    id: 'j-ph-3',
    areaId: 'parable-hollow',
    title: 'Seeds, search, and a trust',
    kicker: 'Parable Hollow',
    unlockAfter: 'ph-seeds',
    body: [
      'Taken together, the sower, the lost sheep, the mustard seed, and the talents sketch a God who speaks, seeks, grows a kingdom from small beginnings, and will ask what was done with a trust.',
      'That is already a case of a sort: not a syllogism, but a coherent portrait. If the portrait is true, the world is personal before it is mechanical.',
    ],
    sources: [
      'Matthew 13:1–23',
      'Matthew 13:31–32',
      'Luke 15:1–7',
      'Matthew 25:14–30',
    ],
  },
  {
    id: 'j-ph-4',
    areaId: 'parable-hollow',
    title: 'The measure you use',
    kicker: 'Parable Hollow',
    unlockAfter: 'ph-debt',
    body: [
      'Matthew 18:21–35 is severe because grace is severe in the opposite direction from cruelty: it creates a world. To be forgiven an unpayable debt and then throttle a neighbor is to live as if the king’s mercy never happened.',
      'Jesus teaches his disciples to pray “forgive us our debts, as we also have forgiven our debtors” (Matt 6:12). The petition assumes the same moral grain.',
    ],
    sources: ['Matthew 18:21–35', 'Matthew 6:12–15'],
  },
  {
    id: 'j-wb-1',
    areaId: 'witness-bench',
    title: 'Of first importance',
    kicker: 'The Witness Bench',
    unlockAfter: 'wb-creed',
    body: [
      '1 Corinthians 15:3–5 is a compressed public claim: death, burial, raising, appearances. Paul presents it as received tradition, not as a private dream. Burial resists a merely “spiritual” death; appearances resist a merely “spiritual” raising.',
      'Whatever one concludes, this is what the churches were already handing on when Paul wrote — a mid-first-century letter appealing to a still-earlier formula.',
    ],
    sources: ['1 Corinthians 15:3–8'],
  },
  {
    id: 'j-wb-2',
    areaId: 'witness-bench',
    title: 'Early is not the same as easy',
    kicker: 'The Witness Bench',
    unlockAfter: 'wb-early',
    body: [
      'Historians cannot rewind the world. They ask how close a report stands to the events, how formulaic it is, and whether the author is appealing to known people (Cephas, the Twelve, James, a large group, Paul himself).',
      'Luke 1:1–4 shows another first-century Christian writer claiming the posture of inquiry among eyewitnesses. That posture can be tested. It should not be sneered out of court in advance.',
    ],
    sources: ['1 Corinthians 15:3–7', 'Luke 1:1–4'],
  },
  {
    id: 'j-wb-3',
    areaId: 'witness-bench',
    title: 'How the past is weighed',
    kicker: 'The Witness Bench',
    unlockAfter: 'wb-method',
    body: [
      'Multiple attestation, embarrassment, early testimony, and contextual credibility are ordinary tools. They do not replace reading. They resist the story that every Christian report is a late pious novel.',
      'Used honestly, they also resist the opposite laziness: “an early creed is already a laboratory proof.” History gives testimony, not a rerun.',
    ],
    sources: [
      'Standard historical method as used in ancient history and historical Jesus studies',
    ],
  },
  {
    id: 'j-wb-4',
    areaId: 'witness-bench',
    title: 'Awkward beginnings',
    kicker: 'The Witness Bench',
    unlockAfter: 'wb-women',
    body: [
      'The tomb stories begin with women, and Luke records that the apostles dismissed them (Luke 24:11). That is an odd opening if the only goal is later public respectability.',
      'Outside the Gospels, Tacitus (Annals 15.44) notes Christus executed under Pilate and a movement that spread to Rome. Josephus (Antiquities 18.63–64) is partly disputed because of later Christian touches, and honesty about that dispute belongs in the dossier.',
    ],
    sources: [
      'Mark 16:1–8',
      'Luke 24:1–11',
      'John 20:1–18',
      'Tacitus, Annals 15.44',
      'Josephus, Antiquities 18.63–64',
    ],
  },
  {
    id: 'j-ob-1',
    areaId: 'observatory',
    title: 'The universe is finely tuned for life',
    kicker: 'The Observatory',
    unlockAfter: 'ob-tuning',
    body: [
      'The universe is finely tuned for life — that fit points to a Designer.',
      'Life-permitting ranges are extravagantly narrow across independent parameters; design predicts a habitable cosmos, blank chance does not.',
      'Three replies get named: necessity, chance (often a multiverse), or design. Necessity fails — these constants are not necessary in that way. Name the multiverse, then mark it: pure assertion, no evidence, not a peer to design.',
    ],
    sources: [
      'Fine-tuning of physical constants and initial conditions (e.g. cosmological constant; Penrose’s low-entropy start — initial condition, not another force dial).',
    ],
  },
  {
    id: 'j-ob-2',
    areaId: 'observatory',
    title: 'A mind that intended a habitable world',
    kicker: 'The Observatory',
    unlockAfter: 'ob-design',
    body: [
      'Fine-tuning is best explained by a mind that intended a habitable world.',
      'Life-permitting ranges are extravagantly narrow; a Designer who wants observers leads us to expect that fit — blank indifference does not.',
      'Name necessity and chance (often a multiverse). Necessity fails. The multiverse is assertion without evidence, not a peer. Hold the Designer.',
    ],
    sources: [
      'Likelihood / fine-tuning arguments (Collins; Rees; Penrose low-entropy as initial condition, not another force dial).',
    ],
  },
  {
    id: 'j-ob-3',
    areaId: 'observatory',
    title: 'The question beneath physics',
    kicker: 'The Observatory',
    unlockAfter: 'ob-leibniz',
    body: [
      'Leibniz’s question — why is there something rather than nothing? — is not retired by a successful cosmological model. Models describe a world that is already given.',
      'When popular writing says the universe came from “nothing,” check whether the word still names a vacuum, a law, or a formalism. Those are somethings. The metaphysical question remains on the table.',
    ],
    sources: [
      'Leibniz, “On the Ultimate Origination of Things”',
      'Standard distinction between physical vacua and metaphysical nothing',
    ],
  },
  {
    id: 'j-ob-4',
    areaId: 'observatory',
    title: 'Life’s open threshold',
    kicker: 'The Observatory',
    unlockAfter: 'ob-life',
    body: [
      'The origin of life is an unfinished scientific story and a live philosophical clue. Cells require specified information and coordinated function. That is not a rumor; it is biology.',
      'Treat the unfinished story as a place for wonder and for more work — and as a mark of mind. Do not stop the lab. Do not shrug the information away.',
    ],
    sources: [
      'Contemporary abiogenesis research as an open program',
      'Genesis 1 as theological, not a lab protocol',
    ],
  },
  {
    id: 'j-fg-1',
    areaId: 'first-gate',
    title: 'Unmoved mover',
    kicker: 'The First Gate',
    unlockAfter: 'fg-mover',
    body: [
      'Aristotle and Aquinas begin with change: the everyday passage from potential to actual. If nothing explains its own becoming, and a stack of unexplained becomings is not an explanation, then there is a first actuality that is not itself a receiver of change.',
      'Read “first” as the bottom of the explanation, not merely the earliest date on a calendar. That is why the argument can be aimed at the present cosmos, not only at a first Tuesday.',
    ],
    sources: [
      'Aristotle, Physics VIII; Metaphysics XII',
      'Aquinas, Summa Theologiae I, q.2, a.3 (First Way)',
    ],
  },
  {
    id: 'j-fg-2',
    areaId: 'first-gate',
    title: 'Necessary being',
    kicker: 'The First Gate',
    unlockAfter: 'fg-contingent',
    body: [
      'Contingent things exist. A world made only of “might-not-have-beens” does not contain the reason why there is anything. Classical theism names the necessary ground God.',
      'Rivals relocate necessity into the universe, or they accept a brute fact. Those are intelligible moves. They are not automatically cheaper. “It just is” is also a metaphysics.',
    ],
    sources: [
      'Aquinas, ST I, q.2, a.3 (Third Way)',
      'Leibniz on sufficient reason',
    ],
  },
  {
    id: 'j-fg-3',
    areaId: 'first-gate',
    title: 'Beginning and cause',
    kicker: 'The First Gate',
    unlockAfter: 'fg-kalam',
    body: [
      'The kalām form is clean: what begins has a cause; the universe began; therefore it has a cause. Clean is not the same as uncontested. The second premise is argued from the impossibility of an infinite past and from contemporary cosmology.',
      'If the form holds, you have a cause of the beginning. Personhood, goodness, and the name of the God of Abraham are further questions — some of them historical.',
    ],
    sources: [
      'al-Ghazālī and the kalām tradition',
      'Contemporary analytic statements (e.g. Craig) and their critics',
    ],
  },
  {
    id: 'j-fg-4',
    areaId: 'first-gate',
    title: 'Honest limits',
    kicker: 'The First Gate',
    unlockAfter: 'fg-limits',
    body: [
      'A sound cosmological argument is already a great deal. It is not yet the sermon on the mount, and it does not need to be. Aquinas does not stop at the Five Ways; he argues onward. The New Testament adds public claims about a particular life, death, and raising.',
      'Pascal’s warning about the God of the philosophers is a warning against stopping. It is not a command to skip the philosophers.',
    ],
    sources: [
      'Aquinas, ST I, qq.2–26 (existence toward attributes)',
      'Pascal, Pensées (God of Abraham / philosophers)',
    ],
  },
  {
    id: 'j-hl-1',
    areaId: 'high-lookout',
    title: 'The moral grain of the world',
    kicker: 'The High Lookout',
    unlockAfter: 'hl-moral',
    body: [
      'Duty presents itself as more than taste. A good God is the ground of a good law — the home that fits. Romans 2 treats that knowledge as widely shared, which is why injustice still has a name.',
      'Romans 2:14–15 treats moral knowledge as widely shared. That is why strangers can still accuse one another of injustice and expect the accusation to mean something.',
    ],
    sources: ['Romans 2:14–15', 'Modern moral arguments and atheist moral realism'],
  },
  {
    id: 'j-hl-2',
    areaId: 'high-lookout',
    title: 'The inside of mind',
    kicker: 'The High Lookout',
    unlockAfter: 'hl-mind',
    body: [
      'Qualia, aboutness, the hard problem, and the norm of reason are not parlor tricks. They are what it is like to be a knower. A story of the world that cannot find a home for mind is a story that cannot find a home for the storyteller.',
      'A living God is the home of mind: not an accident at the end of an indifferent process, but present at the beginning.',
    ],
    sources: [
      'Chalmers on the hard problem',
      'Classical theism on God as living intellect',
    ],
  },
  {
    id: 'j-hl-3',
    areaId: 'high-lookout',
    title: 'Meaning that can be found',
    kicker: 'The High Lookout',
    unlockAfter: 'hl-meaning',
    body: [
      'You can build a local meaning without naming God. The lookout asks whether that meaning is only assembled, or also received — whether the hunger for a final good has an object.',
      'Ecclesiastes refuses to let work and pleasure pretend to be the final good, and also refuses to call them worthless as gifts. That double honesty is part of biblical wisdom.',
    ],
    sources: ['Ecclesiastes 2:24; 9:7–10; 12:13'],
  },
  {
    id: 'j-hl-4',
    areaId: 'high-lookout',
    title: 'Beauty as a signpost',
    kicker: 'The High Lookout',
    unlockAfter: 'hl-beauty',
    body: [
      'Lewis’s argument from desire does not deduct God from a sunset. It notices that beauty wakes a hunger it cannot feed, and that hungers usually correspond to real countries.',
      'Psalm 19 treats the sky as speech. The observatory and the lookout are the same ridge at two hours of the day: measurement at dusk, longing after dark. The trail is unending because the object, if real, is not smaller than a game.',
    ],
    sources: [
      'C. S. Lewis, “The Weight of Glory”; Surprised by Joy',
      'Psalm 19:1–4',
    ],
  },
  {
    id: 'j-trail-1',
    areaId: 'daily-trail',
    title: 'First frost on the rail',
    kicker: 'Daily Trail',
    unlockAfter: 'trail-days-1',
    body: [
      'You walked a morning that will not come again. The town keeps a small mark for that — not a trophy, a thank-you.',
      'The trail will be here tomorrow. If you are away, it waits. Nothing you have already gathered is taken back.',
    ],
    sources: ['A return gift for a single morning on the trail'],
  },
  {
    id: 'j-trail-2',
    areaId: 'daily-trail',
    title: 'A second lantern',
    kicker: 'Daily Trail',
    unlockAfter: 'trail-days-2',
    body: [
      'Two distinct mornings. The path is starting to know your step. Nothing is owed; the bench is still free.',
    ],
    sources: ['A trail note for a second return'],
  },
  {
    id: 'j-trail-3',
    areaId: 'daily-trail',
    title: 'Margin note from the clerk',
    kicker: 'Daily Trail',
    unlockAfter: 'trail-days-3',
    body: [
      'Three distinct days on the trail. The archive clerk left this: “Return is a kind of courage.”',
    ],
    sources: ['A trail note for three unique mornings'],
  },
  {
    id: 'j-trail-5',
    areaId: 'daily-trail',
    title: 'Five weather reports',
    kicker: 'Daily Trail',
    unlockAfter: 'trail-days-5',
    body: [
      'Five different skies. The town does not scold the days you were away. It only saves a page for when you are here.',
    ],
    sources: ['A trail note for five unique mornings'],
  },
  {
    id: 'j-trail-7',
    areaId: 'daily-trail',
    title: 'A week of porches',
    kicker: 'Daily Trail',
    unlockAfter: 'trail-days-7',
    body: [
      'Seven unique mornings. If you miss tomorrow, the trail waits. The marks you already made stay in the journal.',
    ],
    sources: ['A trail note for seven unique mornings'],
  },
]
