import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const packDir = join(here, '../src/content/packs')
const outFile = join(here, '../src/content/packEmbedded.ts')

const files = readdirSync(packDir)
  .filter((name) => name.endsWith('.xml'))
  .sort()

const entries = files.map((name) => {
  const raw = readFileSync(join(packDir, name), 'utf8')
  return `  ${JSON.stringify(name)}: ${JSON.stringify(raw)},`
})

const body = `/** Generated by scripts/embed-packs.mjs — do not edit by hand. */
export const PACK_XML: Record<string, string> = {
${entries.join('\n')}
}
`

writeFileSync(outFile, body, 'utf8')
console.log(`embed-packs: ${files.length} xml files → packEmbedded.ts`)
